### ISSUE TITLE
POM: "fix" empty contributors

### ISSUE THREAD

**Issue by stelfrich** [imcf/noisee#1]
Some nitpicking because I looked at the POM: according to https://github.com/scijava/pom-scijava-base/blob/master/README.md#how-to-override-a-field-with-an-empty-value, [pom.xml#L58-L62](https://github.com/imcf/noisee/blob/master/pom.xml#L58-L62) should read:

```
<contributors>
  <contributor>
    <name>None</name>
  </contributor>
</contributors>
```

**Comment by ehrenfeu** [comment]
Thanks, @stelfrich !
